[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling sharp

[[redirects]]
  from = "/progress.svg"
  to = "/.netlify/functions/progress"
  status = 200
