[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild" # Use esbuild for bundling sharp

[[redirects]]
  from = "/progress-bar.svg"
  to = "/.netlify/functions/progress-bar"
  status = 200

[[redirects]]
  from = "/progress-donut.svg"
  to = "/.netlify/functions/progress-donut"
  status = 200

[[redirects]]
  from = "/pill.svg"
  to = "/.netlify/functions/pill"
  status = 200

[[redirects]]
  from = "/gradient.svg"
  to = "/.netlify/functions/gradient"
  status = 200

[[redirects]]
  from = "/gradient.png"
  to = "/.netlify/functions/gradient"
  status = 200

[[redirects]]
  from = "/datetime.svg"
  to = "/.netlify/functions/datetime"
  status = 200

[[redirects]]
  from = "/user-card.svg"
  to = "/.netlify/functions/user-card"
  status = 200

[[redirects]]
  from = "/stars.svg"
  to = "/.netlify/functions/stars"
  status = 200

[[redirects]]
  from = "/blur.svg"
  to = "/.netlify/functions/blur"
  status = 200

[[redirects]]
  from = "/icon.svg"
  to = "/.netlify/functions/icon"
  status = 200
